steps:
  - id: "gcloud auth 1"
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ["auth", "list"]

  - id: "Build the container image"
    name: gcr.io/cloud-builders/docker
    entrypoint: bash
    dir: 'samples-ar-run'
    args:
      - -c
      - |
        docker build -f Dockerfile . --tag=${_ARTIFACT_RRGISTRY_REPO_NAME}/${_CONTAINER_IMAGE_NAME}:${COMMIT_SHA}
        docker build -f Dockerfile . --tag=${_ARTIFACT_RRGISTRY_REPO_NAME}/${_CONTAINER_IMAGE_NAME}:latest
        docker push ${_ARTIFACT_RRGISTRY_REPO_NAME}/${_CONTAINER_IMAGE_NAME}:${COMMIT_SHA}
        docker push ${_ARTIFACT_RRGISTRY_REPO_NAME}/${_CONTAINER_IMAGE_NAME}:latest

  - id: "Deploy container image to Cloud Run"
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    dir: 'samples-ar-run'
    args:
      - -c
      - |
        cp -a service.yaml.template                                                  service.yaml
        sed -i -e "s/_RUN_SERVICE_REGION/${_RUN_SERVICE_REGION}/g"                   service.yaml
        sed -i -e "s/_RUN_SERVICE_NAME/${_RUN_SERVICE_NAME}/g"                       service.yaml
        sed -i -e "s/_RUN_SERVICE_PORT/${_RUN_SERVICE_PORT}/g"                       service.yaml
        echo "debug 1"
        sed -i -e "s/_ARTIFACT_RRGISTRY_REPO_NAME/${_ARTIFACT_RRGISTRY_REPO_NAME}/g" service.yaml
        cat service.yaml
        sed -i -e "s/_CONTAINER_IMAGE_NAME/${_CONTAINER_IMAGE_NAME}/g"               service.yaml
        sed -i -e "s/_TAG/${COMMIT_SHA}/g"                                           service.yaml
        sed -i -e "s/_SERVICE_ACCOUNT/${_SERVICE_ACCOUNT}/g"                         service.yaml
        cat service.yaml
        # gcloud run services replace service.yaml --platform managed --project ${PROJECT_ID}
        # gcloud run services update ${_RUN_SERVICE_NAME} --allow-unauthenticated --project ${PROJECT_ID} 
        # gcloud run deploy ${_RUN_SERVICE_NAME} --platform managed --image ${_ARTIFACT_RRGISTRY_REPO_NAME}/${_CONTAINER_IMAGE_NAME}:${COMMIT_SHA} --region ${_RUN_SERVICE_REGION} --port ${_RUN_SERVICE_PORT} --allow-unauthenticated

logsBucket: gs://${_GCS_BUCKET}

substitutions:
  _ARTIFACT_RRGISTRY_REPO_NAME: 'Your Artifact Registry Repository Name' 
  _CONTAINER_IMAGE_NAME: 'Your Container Image Name'
  _RUN_SERVICE_NAME: 'Your Cloud Run Service Name'
  _RUN_SERVICE_REGION: 'Your Cloud Run Service Region'
  _RUN_SERVICE_PORT: 'Your Cloud Run Service Port'
  _GCS_BUCKET: 'Your Google Cloud Storage Bucket using Cloud Build logs'
  _SERVICE_ACCOUNT: 'Service Account using Your Cloud Run Service'
timeout: 86400s
