steps:
  - id: "gcloud auth 1"
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ["auth", "list"]
  - id: "Build the container image"
    name: gcr.io/cloud-builders/docker
    entrypoint: bash
    dir: 'samples-ar-run'
    args:
      - -c
      - |
        docker build -f Dockerfile . --tag=${_ARTIFACT_RRGISTRY_REPO_NAME}/${_CONTAINER_IMAGE_NAME}:${COMMIT_SHA}
        docker build -f Dockerfile . --tag=${_ARTIFACT_RRGISTRY_REPO_NAME}/${_CONTAINER_IMAGE_NAME}:latest
        docker push ${_ARTIFACT_RRGISTRY_REPO_NAME}/${_CONTAINER_IMAGE_NAME}:${COMMIT_SHA}
        docker push ${_ARTIFACT_RRGISTRY_REPO_NAME}/${_CONTAINER_IMAGE_NAME}:latest

  - id: "Deploy container image to Cloud Run"
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run deploy ${_RUN_SERVICE_NAME} --platform managed --image ${_ARTIFACT_RRGISTRY_REPO_NAME}/${_CONTAINER_IMAGE_NAME}:${COMMIT_SHA} --region ${_RUN_SERVICE_REGION} --port ${_RUN_SERVICE_PORT} --allow-unauthenticated

logsBucket: gs://${_GCS_BUCKET}

substitutions:
  _ARTIFACT_RRGISTRY_REPO_NAME: 'Your Artifact Registry Repository Name' 
  _CONTAINER_IMAGE_NAME: 'Your Container Image Name'
  _RUN_SERVICE_NAME: 'Your Cloud Run Service Name'
  _RUN_SERVICE_REGION: 'Your Cloud Run Service Region'
  _RUN_SERVICE_PORT: 'Your Cloud Run Service Port'
  _GCS_BUCKET: 'Your Google Cloud Storage Bucket using Cloud Build logs'
timeout: 86400s
